### ISSUE TITLE
Can't dynamically register client in oauth.tools

### ISSUE THREAD

**Issue by travisspencer** [phantauth/phantauth-feedback#3]
I'm trying to register a dynamic client in oauth.tools (an RP test tool). I created an environment in that tool by entering `https://phantauth.net/.well-known/openid-configuration` as the metadata endpoint in the environment settings. Then, on the client tab of that environment, I tried to register a dynamic client. I tried to register just the code and implicit grant type with the scope `openid` and oauth.tool's redirects. I kept getting an error though, so I tried to provide more metadata during registration. It seems though that it wants something that oauth.tools isn't providing. Here's the curl command that's equivalent to what the tool was sending to register the client:

```
curl -s -X POST https://phantauth.net/auth/register -H 'Content-Type: application/json' -d '{"token_endpoint_auth_method":"client_secret_post","scope":"openid","grant_types":["authorization_code","implicit"],"redirect_uris":["https://oauth.tools/callback/implicit","https://oauth.tools/callback/code","https://oauth.tools/callback/hybrid"]}'
```

The error that I get from this is `{"error_description":"The value must not be null or empty string","error":"illegal_argument"}` and a server 500.

Any idea what's preventing this interop?

**Comment by szkiba** [comment]
Sorry, dynamic client registration is not a well tested part of PhantAuth and since PhantAuth is stateless it is not a real registration. In registration endpoint reply you will get a "client_id" which is basically a JWT with all client data encoded. It mean a bit long client_id, so maybe some client will have problem with the length.

About the current problem: you should add some fields:
 - software_id
 - software_version
 - tos_uri
 - policy_uri
 - client_uri
 - logo_uri

Require these field is a mistake in PhantAuth, and I'll remove this. If you provide these fields as workarond (uri should be paresable URI), it will work.
Alternate solution is instead of dynamic regisration, just use any client_id you like, and genereate client_secret value at https://phantauth.net

**Comment by travisspencer** [comment]
Just retested this, and it's the same. Any updates?

**Comment by szkiba** [comment]
Sorry for the delay (my daughter had a wedding party in last weekend so the last few weeks was about preparation). I hope on this week I'll fix the problem.

**Comment by szkiba** [comment]
Dear @travisspencer, dynamic client registration issue fixed. I tested it with oauth.tools code, hybrid, resource owner password, introspect, userinfo flows, it seem working.
(other flows not implemented yet but maybe I'll implement because oauth.tools so motivating)
BTW it would be nice if client_name and logo_uri would have a default value (ie: "oauth.tools - code flow"), because of login and consent screen.

**Comment by szkiba** [comment]
BTW the implicit flow in oauth.tools is only OAuth 2.0 and boken for OpenID Connect.
response type parameter should contains "id_token token" for OpenID Connectd so this flow currently doesnt work with PhantAuth.
Fixing tipp: if "openid" in scope list, the tool should add "id_token" to response types.

**Comment by travisspencer** [comment]
I tested DCR as well, @szkiba . Working fine. The reason taht the client doesn't automatically set a name or logo is because you could have many of them for a certain demo or setup. I often have a handful. Will keep this tip in mind though.

If you want to do OIDC implicit, use "hybrid flow" in oauth.tools and change the response type. Like this:

<img width="874" alt="Screenshot 2019-10-08 at 7 19 16 PM" src="https://user-images.githubusercontent.com/2499235/66417613-afb0a600-ea00-11e9-9372-027af07271a5.png">

Agree though that implicit seems more intuitive. Will consider updating this.

Thanks again for fixing, and providing feedback on oauth.tools. If you have any other tips/suggestions, please let me know.
